name: Build Project

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Copy the Jar File
        run: cp ./target/pdf-bill-generator-jar-with-dependencies.jar ./exec/billGenerator.jar

      - name: Commit Version Changes to Main
        uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: Generated the Jar